### ISSUE TITLE
Setting custom coverage file path

### ISSUE THREAD

**Issue by dragn** [juanpabloaj/vim-istanbul#1]
Setting `g:coverage_json_path` does not work, because file path is not passed to python script (see [this line](https://github.com/juanpabloaj/vim-istanbul/blob/master/autoload/istanbul.py#L9)).
(I may be able to file a pull request later)

**Comment by juanpabloaj** [comment]
yes, you are right. thanks for report this issue.

I would appreciate a pull request ;)

**Comment by dragn** [comment]
The problem is that when I call `:IstanbulShow` nothing happens :(, though I do have a valid coverage.json...
Trying to debug...

**Comment by juanpabloaj** [comment]
when I get home, I will try to fix the problem.

you can generate sample files and the steps to reproduce the problem ?

**Comment by dragn** [comment]
I tracked it down. My `coverage.json` contains file paths _relative_ to root. But in `istanbul.py` you look up the file by absolute path.
I think that we could check whether the first character in the path is `/` to determine if it absolute or not.

**Comment by juanpabloaj** [comment]
@dragn if this merge fix you problem, please close this issue.

**Comment by dragn** [comment]
Checked on master
