### ISSUE TITLE
Port to emacs

### ISSUE THREAD

**Issue by ghost** [juanpabloaj/vim-istanbul#5]
Would you guys know how-to port this to emacs?

**Comment by juanpabloaj** [comment]
sorry but I never used emacs :/

this plugin/script take the information from the `coverage/coverage.json`  file generated by istambul, maybe you can started a fork for emacs.

**Comment by ghost** [comment]
I'll have to take a look at how-to develop plugins for emacs.

**Comment by ghost** [comment]
For people reading this later, I switched to Atom recently, no emacs plugin.

**Comment by FossiFoo** [comment]
shameless plug: i use the istanbul lcov reporter alongside (my fork of) coverlay to color coverage

**Comment by ghost** [comment]
@FossiFoo awesome, I'll give it a try.
